export const property = {
  movId: 1,
  person: 'Fosco',
  level: 'Avancé',
  title: 'Title ici Lorem Ipsum A',
  description: 'Description Here',
  embedId: 'oZlOWecrueo',
  imageUrl: 'https://i.ibb.co/7SQ0XHn/image-2.png',
};

export const propertyyyyy = [
  {
    movId: 11,
    person: 'Fosco',
    level: 'Avancé',
    title: 'Title ici Lorem Ipsum A',
    description: 'Description Here',
    embedId: 'oZlOWecrueo',
    imageUrl: 'https://i.ibb.co/7SQ0XHn/image-2.png',
  },
  {
    movId: 12,
    person: 'Fosco',
    level: 'Avancé',
    title: 'Title ici Lorem Ipsum A',
    description: 'Description Here',
    embedId: 'AN21Erb0btM',
    imageUrl: 'https://i.ibb.co/7SQ0XHn/image-2.png',
  },
  {
    movId: 13,
    person: 'Fosco',
    level: 'Avancé',
    title: 'Title ici Lorem Ipsum A',
    description: 'Description Here',
    embedId: 'rMQUI55vo4I',
    imageUrl: 'https://i.ibb.co/7SQ0XHn/image-2.png',
  },
  {
    movId: 21,
    person: 'Renping',
    level: 'Avancé',
    title: 'Title ici Lorem Ipsum A',
    description: 'Description Here',
    embedId: 'U6F4BmYhRiQ',
    imageUrl: 'https://i.ibb.co/7SQ0XHn/image-2.png',
  },
  {
    movId: 22,
    person: 'Renping',
    level: 'Avancé',
    title: 'Title ici Lorem Ipsum A',
    description: 'Description Here',
    embedId: 'jBOBdplWjVM',
    imageUrl: 'https://i.ibb.co/7SQ0XHn/image-2.png',
  },
  {
    movId: 23,
    person: 'Renping',
    level: 'Avancé',
    title: 'Title ici Lorem Ipsum A',
    description: 'Description Here',
    embedId: 'Q5e9nlZQYho',
    imageUrl: 'https://i.ibb.co/7SQ0XHn/image-2.png',
  },
  {
    movId: 32,
    person: 'Sofia',
    level: 'Intermédiaire',
    title: 'Title ici Lorem Ipsum A',
    description: 'Description Here',
    embedId: 'MhuLVQNaR6A',
    imageUrl: 'https://i.ibb.co/7SQ0XHn/image-2.png',
  },
  {
    movId: 33,
    person: 'Sofia',
    level: 'Intermédiaire',
    title: 'Title ici Lorem Ipsum A',
    description: 'Description Here',
    embedId: 'QLUm-XLqWgA',
    imageUrl: 'https://i.ibb.co/7SQ0XHn/image-2.png',
  },
];
